### ISSUE TITLE
raw_input() replaced by input() in Python 3

### ISSUE THREAD

**Issue by bretthandrews** [sdss/sdss_access#1]
As reported in sdss/marvin#218, if the user does not have their `.netrc` file permissions set to 600, then calling `raw_input()` to bring up the interactive authentication prompt will throw an error in Python 3 because this function was replaced with `input()`.

**Comment by joelbrownstein** [comment]
Hi Bret,,

I don't think this is the right fix, and would now be broken in python2.

i.e. What is the difference between raw_input() and input() in Python ...<https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjDj--Cn5rTAhUG3yYKHX_ND0cQFggfMAE&url=https%3A%2F%2Fwww.quora.com%2FWhat-is-the-difference-between-raw_input-and-input-in-Python&usg=AFQjCNFMy3i0jBKZWP4qf2ZM-Dq3ckmI4A> says:

In Python 2.7, raw_input() returns a string, and input() tries to run the input as a Python expression.
Since getting a string was almost always what you wanted, Python 3 does that with input().
If you ever want the old behaviour, eval(input()) it works.

try thin in python2

In [1]: response = input("What: ")
What: something
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-0d2bda49faa3> in <module>()
----> 1 response = input("What: ")

<string> in <module>()

NameError: name 'something' is not defined


On Apr 10, 2017, at 10:59 AM, Brett Andrews <notifications@github.com<mailto:notifications@github.com>> wrote:


As reported in sdss/marvin#218<https://github.com/sdss/marvin/issues/218>, if the user does not have their .netrc file permissions set to 600, then calling raw_input() to bring up the interactive authentication prompt will throw an error in Python 3 because this function was replaced with input().

**Comment by bretthandrews** [comment]
Hi Joel,

I used the six.py version of `input()`, which uses `raw_input()` if Python 2 and `input()` for Python 3.

Cheers,
Brett

**Comment by joelbrownstein** [comment]
That makes sense!

On Apr 10, 2017, at 1:03 PM, Brett Andrews <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Joel,

I used the six.py version of input(), which uses raw_input() if Python 2 and input() for Python 3.

Cheers,
Brett
