### ISSUE TITLE
force_modules or other flag should retain user-defined envvars

### ISSUE THREAD

**Issue by blanton144** [sdss/sdss_access#25]
The Path() object currently defines the environmental variables within a Python according to a specific tree version.

For example, for release='sdss5', if I define ROBOSTRATEGY_DATA in my environment, and then enter Python and instantiate a Path object, it will alter my environmental variables and ROBOSTRATEGY_DATA will have whatever value is in the config file for sdss5. 

This behavior is quite useful for data users, who should be accessing a very specific set of released data. For development and pipelines, it is not clearly as useful, because sometimes we need fine-grained control of the envvars; requiring a new tree version for every individual test is burdensome.

The documentation for force_modules=True makes it sound as if it will force sdss_access to respect existing envvars, but it does not seem to do so (i.e. it changes ROBOSTRATEGY_DATA even if it is set). Brian tells me it works only with a subset of the envvars, though I don't see in the code how that happens (in fact, I was unable to figure out WHY it fails, so I don't understand the code!). 

It would be useful to have an option which makes sdss_access respect all existing environmental variables (or some subset of them).

**Comment by havok2063** [comment]
@blanton144 Thanks for pointing this out.  It seems this use of `sdss_access` got lost during a tighter integration with `tree`.  This should be straightforward enough to implement.  

The docs should be clarified around `force_modules`.  This keyword was meant to apply only to paths that point to files in checked out software products from svn or github, e.g. files in `mangacore`, or `platedesign`.   `force_modules` was used to revert those paths back to local pointers to checked out locations rather than from defined tags of software products.  `sdss_access` handles paths to files in software products a bit differently than paths to files on the SAS, described [here](https://sdss-access.readthedocs.io/en/latest/intro.html#accessing-paths-to-data-files-in-svn).  You can see how the `force_modules` keyword is currently used [in Path.full](https://github.com/sdss/sdss_access/blob/master/python/sdss_access/path/path.py#L585) which also calls [this function](https://github.com/sdss/sdss_access/blob/fac5ae1c682559f6c0a17873fe696d319611381b/python/sdss_access/path/path.py#L613)

**Comment by havok2063** [comment]
@blanton144 I've released a fix for this.  I've added a new `preserve_envvars` keyword argument which can be set either  to `True` to preserve the entire original user's `os.environ` or to a list of environment variables to preserve only a subset.  You'll need either the `master` branches of both `tree` and `sdss_access` or the latest releases/tags of `tree 3.0.6` and `sdss_access 1.1.1.`.  See the [sdss_access docs](https://sdss-access.readthedocs.io/en/latest/intro.html#environment-paths).
